"""PDF Service — generates triage and physician reports.

Uses fpdf2 (pure Python) for PDF generation with KI branding.
Reports include RETTS color coding, ensemble analysis, and clinical data.
"""

from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING, Optional

from fpdf import FPDF

if TYPE_CHECKING:
    from src.engines.agreement_engine import (
        DifferentialAgreement,
        ManagementAgreement,
        TriageAgreement,
    )
    from src.models.vitals import VitalSigns
    from src.services.session_manager import PatientSession


# --------------------------------------------------------------------------- #
# Color constants (RGB tuples)
# --------------------------------------------------------------------------- #

_HEADER_RGB = (79, 4, 51)       # KI Purple #4F0433
_SECONDARY_RGB = (135, 0, 82)   # KI Secondary #870052
_MUTED_RGB = (102, 102, 102)    # Gray text
_BLACK = (0, 0, 0)
_WHITE = (255, 255, 255)
_ERROR_RGB = (184, 65, 69)      # Red for alerts

# Unicode → latin-1 safe replacements for built-in Helvetica font
_UNICODE_REPLACEMENTS = {
    "\u2014": "-",   # em-dash
    "\u2013": "-",   # en-dash
    "\u2018": "'",   # left single quote
    "\u2019": "'",   # right single quote
    "\u201c": '"',   # left double quote
    "\u201d": '"',   # right double quote
    "\u2026": "...", # ellipsis
    "\u2192": "->",  # right arrow
    "\u2190": "<-",  # left arrow
    "\u2265": ">=",  # greater-than-or-equal
    "\u2264": "<=",  # less-than-or-equal
    "\u00b7": "-",   # middle dot
}


def _sanitize(text: str) -> str:
    """Replace non-latin-1 characters so built-in Helvetica can render them."""
    for char, replacement in _UNICODE_REPLACEMENTS.items():
        text = text.replace(char, replacement)
    # Final fallback: encode to latin-1, replacing anything else with ?
    return text.encode("latin-1", errors="replace").decode("latin-1")

RETTS_RGB = {
    "RED":    (184, 65, 69),
    "ORANGE": (255, 135, 111),
    "YELLOW": (245, 154, 0),
    "GREEN":  (84, 185, 134),
    "BLUE":   (77, 181, 188),
}

_RETTS_TEXT_RGB = {
    "RED":    _WHITE,
    "ORANGE": _BLACK,
    "YELLOW": _BLACK,
    "GREEN":  _BLACK,
    "BLUE":   _BLACK,
}


# --------------------------------------------------------------------------- #
# Base PDF class with KI branding
# --------------------------------------------------------------------------- #

class MedleyPDF(FPDF):
    """Base PDF class with Triage-Medley branding."""

    def __init__(self, report_type: str = "Triage Report"):
        super().__init__()
        self.report_type = report_type
        self.set_auto_page_break(auto=True, margin=20)

    def cell(self, *args, **kwargs):
        """Override to sanitize text for latin-1 font compatibility."""
        if args:
            args = list(args)
            for i, a in enumerate(args):
                if isinstance(a, str):
                    args[i] = _sanitize(a)
            args = tuple(args)
        for k, v in kwargs.items():
            if isinstance(v, str):
                kwargs[k] = _sanitize(v)
        return super().cell(*args, **kwargs)

    def multi_cell(self, *args, **kwargs):
        """Override to sanitize text for latin-1 font compatibility."""
        if args:
            args = list(args)
            for i, a in enumerate(args):
                if isinstance(a, str):
                    args[i] = _sanitize(a)
            args = tuple(args)
        for k, v in kwargs.items():
            if isinstance(v, str):
                kwargs[k] = _sanitize(v)
        return super().multi_cell(*args, **kwargs)

    def header(self):
        self.set_fill_color(*_HEADER_RGB)
        self.rect(0, 0, 210, 18, "F")
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(*_WHITE)
        self.set_xy(10, 3)
        self.cell(0, 12, f"Triage-Medley  |  {self.report_type}", align="L")
        self.ln(20)

    def footer(self):
        self.set_y(-20)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*_MUTED_RGB)
        self.cell(
            0, 5,
            f"Generated by Triage-Medley  |  "
            f"Page {self.page_no()}/{{nb}}  |  "
            f"{datetime.now().strftime('%Y-%m-%d %H:%M')}",
            align="C",
            new_x="LMARGIN", new_y="NEXT",
        )
        self.set_font("Helvetica", "", 6)
        self.cell(
            0, 5,
            "(c) 2026 SMAILE (Stockholm Medical AI and Learning Environments), "
            "Karolinska Institutet.",
            align="C",
        )

    # -- helpers ------------------------------------------------------------ #

    def section_heading(self, text: str) -> None:
        self.ln(2)
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(*_HEADER_RGB)
        self.cell(0, 8, text, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(*_HEADER_RGB)
        y = self.get_y()
        self.line(10, y, 200, y)
        self.ln(3)
        self.set_text_color(*_BLACK)

    def kv(self, key: str, value: str, bold_value: bool = False) -> None:
        """Key: value row with text wrapping for long values."""
        self.set_x(self.l_margin)  # Always start at left margin
        self.set_font("Helvetica", "B", 9)
        self.cell(50, 6, f"{key}:")
        self.set_font("Helvetica", "B" if bold_value else "", 9)
        # Use multi_cell for wrapping; temporarily shift left margin so
        # wrapped lines align with the value start
        old_l_margin = self.l_margin
        self.set_left_margin(old_l_margin + 50)
        self.multi_cell(0, 6, str(value))
        self.set_left_margin(old_l_margin)
        self.set_x(old_l_margin)  # Reset x for next element

    def retts_badge(self, level: str) -> None:
        """Inline colored RETTS level pill."""
        rgb = RETTS_RGB.get(level.upper(), _MUTED_RGB)
        text_rgb = _RETTS_TEXT_RGB.get(level.upper(), _BLACK)
        self.set_fill_color(*rgb)
        self.set_text_color(*text_rgb)
        self.set_font("Helvetica", "B", 10)
        w = self.get_string_width(level) + 10
        self.cell(w, 7, level, fill=True, align="C")
        self.set_text_color(*_BLACK)

    def bullet(self, text: str, indent: int = 4) -> None:
        """Single bullet point with text wrapping."""
        self.set_font("Helvetica", "", 9)
        old_l_margin = self.l_margin
        x_start = old_l_margin + indent
        self.set_x(x_start)
        self.set_left_margin(x_start + 6)  # Wrapped lines indent past "- "
        self.multi_cell(0, 5, f"- {text}")
        self.set_left_margin(old_l_margin)
        self.set_x(old_l_margin)  # Reset x for next element

    def alert_text(self, text: str) -> None:
        """Red alert text."""
        self.set_x(self.l_margin)  # Reset to left margin
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*_ERROR_RGB)
        self.multi_cell(0, 5, text)
        self.set_text_color(*_BLACK)


def _get_val(obj, attr, default=None):
    """Helper to get attribute or dict key robustly."""
    if obj is None: return default
    if isinstance(obj, dict): return obj.get(attr, default)
    return getattr(obj, attr, default)

# --------------------------------------------------------------------------- #
# Shared rendering helpers
# --------------------------------------------------------------------------- #

def _render_demographics(pdf: MedleyPDF, patient: PatientSession) -> None:
    pdf.section_heading("Patient Information")
    pdf.kv("Name", patient.name)
    pdf.kv("Age / Sex", f"{patient.age}y {patient.sex}")
    pdf.kv("Arrival", patient.arrival_time.strftime("%Y-%m-%d %H:%M"))
    _ap = patient.arrival_pathway
    pdf.kv("Pathway", (_get_val(_ap, "value", str(_ap))).replace("_", " ").title())
    pdf.kv("Chief Complaint", patient.speech_text)
    pdf.ln(3)


def _render_vitals(pdf: MedleyPDF, patient: PatientSession) -> None:
    fc = patient.full_context
    if not fc:
        return
    v = _get_val(fc, "vitals")
    if not v: return
    
    pdf.section_heading("Vital Signs")
    headers = ["HR (bpm)", "BP (mmHg)", "RR (/min)", "SpO2 (%)", "Temp (C)", "AVPU"]
    values = [
        str(_get_val(v, "heart_rate", "N/A")),
        f"{_get_val(v, 'systolic_bp', 'N/A')}/{_get_val(v, 'diastolic_bp', 'N/A')}",
        str(_get_val(v, "respiratory_rate", "N/A")),
        str(_get_val(v, "spo2", "N/A")),
        f"{float(_get_val(v, 'temperature', 0)):.1f}",
        _get_val(_get_val(v, "consciousness", "Alert"), "value", str(_get_val(v, "consciousness", "Alert"))),
    ]
    col_w = 30
    # Header row
    pdf.set_font("Helvetica", "B", 8)
    for h in headers:
        pdf.cell(col_w, 5, h, border=1, align="C")
    pdf.ln()
    # Value row
    pdf.set_font("Helvetica", "", 9)
    for val in values:
        pdf.cell(col_w, 6, val, border=1, align="C")
    pdf.ln(6)


def _render_asr(pdf: MedleyPDF, patient: PatientSession) -> None:
    asr = patient.asr_result
    if not asr:
        return
    pdf.section_heading("Speech Recognition (Dual-ASR)")
    pdf.kv("Confidence", f"{_get_val(asr, 'confidence_score', 0):.0%}")
    pdf.kv("Disagreements", str(_get_val(asr, 'disagreement_count', 0)))
    if _get_val(asr, 'has_critical_disagreements', False):
        pdf.alert_text("Critical ASR disagreements detected on clinically significant terms")
    
    disagreements = _get_val(asr, "disagreements", [])
    for d in disagreements:
        resolved = f" -> {_get_val(d, 'resolved_to')}" if _get_val(d, 'resolved') else " (unresolved)"
        pdf.set_font("Helvetica", "", 8)
        indent_x = pdf.l_margin + 4
        pdf.set_x(indent_x)
        old_lm = pdf.l_margin
        pdf.set_left_margin(indent_x)
        pdf.multi_cell(
            0, 5,
            f'MedASR: "{_get_val(d, "medasr_word")}" vs Whisper: "{_get_val(d, "whisper_word")}" '
            f'[{_get_val(d, "clinical_significance", "moderate")}]{resolved}',
        )
        pdf.set_left_margin(old_lm)
    pdf.ln(3)


def _render_ehr_risk_flags(pdf: MedleyPDF, patient: PatientSession) -> None:
    fc = patient.full_context
    if not fc: return
    ehr = _get_val(fc, "ehr")
    if not ehr: return
    
    risk_flags = _get_val(ehr, "risk_flags", [])
    if not risk_flags:
        return
    pdf.section_heading("EHR Risk Flags")
    for rf in risk_flags:
        pdf.set_font("Helvetica", "B", 9)
        sev_label = str(_get_val(rf, "severity", "moderate")).upper()
        indent_x = pdf.l_margin + 4
        pdf.set_x(indent_x)
        old_lm = pdf.l_margin
        pdf.set_left_margin(indent_x)
        pdf.multi_cell(
            0, 5,
            f"[{sev_label}] {_get_val(rf, 'flag_type')}: {_get_val(rf, 'description')}",
        )
        pdf.set_left_margin(old_lm)
    pdf.ln(3)


def _render_triage_result(pdf: MedleyPDF, patient: PatientSession) -> None:
    ta = patient.triage_agreement
    if not ta:
        return
    pdf.section_heading("Ensemble Triage Result")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(30, 7, "Final Level: ")
    _fl = _get_val(ta, "final_level")
    pdf.retts_badge(_get_val(_fl, "value", str(_fl)))
    pdf.ln(9)
    _al = _get_val(ta, "agreement_level")
    pdf.kv("Agreement", f"{_get_val(_al, 'value', str(_al))} ({_get_val(ta, 'agreement_ratio', 0):.0%})")
    pdf.kv("Total Voters", str(_get_val(ta, 'total_voters', 0)))

    # Vote distribution
    pdf.set_x(pdf.l_margin)
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(0, 6, "Vote Distribution:", new_x="LMARGIN", new_y="NEXT")
    vote_dist = _get_val(ta, "vote_distribution", {})
    for level_str, count in sorted(
        vote_dist.items(),
        key=lambda x: ["RED", "ORANGE", "YELLOW", "GREEN", "BLUE"].index(x[0])
        if x[0] in ["RED", "ORANGE", "YELLOW", "GREEN", "BLUE"] else 99,
    ):
        pdf.set_font("Helvetica", "", 9)
        pdf.cell(0, 5, f"  {level_str}: {count}/{_get_val(ta, 'total_voters', 1)}", new_x="LMARGIN", new_y="NEXT")

    esc_reason = _get_val(ta, "escalation_reason")
    if esc_reason:
        pdf.ln(2)
        pdf.alert_text(f"ESCALATION: {esc_reason}")

    if _get_val(ta, "requires_senior_review", False):
        pdf.alert_text("SENIOR REVIEW REQUIRED")

    dissenting = _get_val(ta, "dissenting_models", [])
    if dissenting:
        pdf.set_x(pdf.l_margin)
        pdf.set_font("Helvetica", "I", 8)
        pdf.multi_cell(0, 5, f"Dissenting: {', '.join(dissenting)}")

    dont_miss = _get_val(ta, "dont_miss_alerts", [])
    if dont_miss:
        pdf.ln(2)
        pdf.set_x(pdf.l_margin)
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(0, 5, "Don't-Miss Alerts:", new_x="LMARGIN", new_y="NEXT")
        for alert in dont_miss:
            pdf.bullet(alert)
    pdf.ln(3)


def _render_cross_engine(pdf: MedleyPDF, patient: PatientSession) -> None:
    te = patient.triage_ensemble
    if not te: return
    engine_outs = _get_val(te, "engine_outputs", [])
    if len(engine_outs) < 2:
        return
    from src.engines.agreement_engine import analyze_engine_disagreement
    ed = analyze_engine_disagreement(engine_outs)
    if not ed:
        return
    pdf.section_heading("Cross-Engine Comparison")
    engine_lvls = _get_val(ed, "engine_levels", {})
    for engine_name, level in engine_lvls.items():
        pdf.kv(engine_name, level, bold_value=True)
    if not _get_val(ed, "engines_agree", True):
        pdf.ln(1)
        pdf.set_x(10)
        pdf.set_font("Helvetica", "I", 8)
        pdf.multi_cell(0, 4, _get_val(ed, "clinical_action", ""))
    pdf.ln(3)


def _render_nurse_override(pdf: MedleyPDF, patient: PatientSession) -> None:
    if not patient.overrides:
        return
    pdf.section_heading("Nurse Override")
    last = patient.overrides[-1]
    pdf.kv("From", str(last.get("original", "N/A")))
    pdf.kv("To", str(last.get("override_to", "N/A")))
    pdf.kv("Reason", str(last.get("reason", "Not specified")))
    pdf.ln(3)


def _render_management_category(pdf: MedleyPDF, heading: str, items: list[str]) -> None:
    """Render a management category (consensus items)."""
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(0, 6, f"{heading}:", new_x="LMARGIN", new_y="NEXT")
    if items:
        for item in items:
            pdf.bullet(item)
    else:
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(*_MUTED_RGB)
        pdf.cell(0, 5, "  No consensus items", new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(*_BLACK)


def _render_individual_model_items(pdf: MedleyPDF, patient: PatientSession, promoted: bool = False) -> None:
    """Render non-consensus items from individual models."""
    ma = patient.management_agreement
    me = patient.management_ensemble
    if not ma or not me:
        return

    common_inv = _get_val(ma, "common_investigations", [])
    common_img = _get_val(ma, "common_imaging", [])
    common_med = _get_val(ma, "common_medications", [])

    consensus_inv = {str(x).lower() for x in common_inv}
    consensus_img = {str(x).lower() for x in common_img}
    consensus_med = {str(x).lower() for x in common_med}

    extra_inv: list[tuple[str, str]] = []
    extra_img: list[tuple[str, str]] = []
    extra_med: list[tuple[str, str]] = []

    model_outputs = _get_val(me, "model_outputs", [])
    for output in model_outputs:
        mid = _get_val(output, "model_id", "AI")
        for item in _get_val(output, "investigations", []):
            if str(item).lower() not in consensus_inv:
                extra_inv.append((item, mid))
        for item in _get_val(output, "imaging", []):
            if str(item).lower() not in consensus_img:
                extra_img.append((item, mid))
        for item in _get_val(output, "medications", []):
            if str(item).lower() not in consensus_med:
                extra_med.append((item, mid))

    has_extras = extra_inv or extra_img or extra_med
    if not has_extras:
        return

    pdf.ln(2)

    if promoted:
        # Show per-model breakdown as primary content
        for output in model_outputs:
            inv = _get_val(output, "investigations", [])
            img = _get_val(output, "imaging", [])
            med = _get_val(output, "medications", [])
            if not inv and not img and not med:
                continue
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*_HEADER_RGB)
            pdf.cell(0, 6, f"{_get_val(output, 'model_id', 'AI')}:", new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(*_BLACK)
            if inv:
                pdf.set_font("Helvetica", "I", 8)
                pdf.cell(0, 5, "  Investigations:", new_x="LMARGIN", new_y="NEXT")
                for item in inv:
                    pdf.bullet(item, indent=8)
            if img:
                pdf.set_font("Helvetica", "I", 8)
                pdf.cell(0, 5, "  Imaging:", new_x="LMARGIN", new_y="NEXT")
                for item in img:
                    pdf.bullet(item, indent=8)
            if med:
                pdf.set_font("Helvetica", "I", 8)
                pdf.cell(0, 5, "  Medications:", new_x="LMARGIN", new_y="NEXT")
                for item in med:
                    pdf.bullet(item, indent=8)
            pdf.ln(2)
        return

    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(*_SECONDARY_RGB)
    pdf.cell(0, 6, "Additional Items (Individual Models):", new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(*_BLACK)

    seen: set[str] = set()
    for label, items_list in [("Investigations", extra_inv), ("Imaging", extra_img), ("Medications", extra_med)]:
        unique = []
        for item, model in items_list:
            if str(item).lower() not in seen:
                seen.add(str(item).lower())
                unique.append((item, model))
        if unique:
            pdf.set_font("Helvetica", "I", 8)
            pdf.cell(0, 5, f"  {label}:", new_x="LMARGIN", new_y="NEXT")
            for item, model in unique:
                pdf.set_font("Helvetica", "", 8)
                item_x = pdf.l_margin + 8
                pdf.set_x(item_x)
                old_lm = pdf.l_margin
                pdf.set_left_margin(item_x + 6)  # Wrap indent past "- "
                pdf.multi_cell(0, 5, f"- {item} ({model})")
                pdf.set_left_margin(old_lm)


def _render_approved_list(pdf: MedleyPDF, heading: str, items: list[str]) -> None:
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(0, 6, f"{heading}:", new_x="LMARGIN", new_y="NEXT")
    if items:
        for item in items:
            pdf.bullet(item)
    else:
        pdf.set_font("Helvetica", "I", 8)
        pdf.cell(0, 5, "  None specified", new_x="LMARGIN", new_y="NEXT")


# --------------------------------------------------------------------------- #
# Public API
# --------------------------------------------------------------------------- #

def generate_triage_pdf(patient: PatientSession) -> bytes:
    """Generate triage report PDF. Returns bytes for st.download_button."""
    pdf = MedleyPDF("Triage Report")
    pdf.alias_nb_pages()
    pdf.add_page()

    _render_demographics(pdf, patient)
    _render_vitals(pdf, patient)
    _render_asr(pdf, patient)
    _render_ehr_risk_flags(pdf, patient)
    _render_triage_result(pdf, patient)
    _render_cross_engine(pdf, patient)
    _render_nurse_override(pdf, patient)

    # Timestamp
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(
        0, 5,
        f"Report generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        new_x="LMARGIN", new_y="NEXT",
    )

    return bytes(pdf.output())


def generate_physician_pdf(patient: PatientSession) -> bytes:
    """Generate physician report PDF. Returns bytes for st.download_button."""
    pdf = MedleyPDF("Physician Report")
    pdf.alias_nb_pages()
    pdf.add_page()

    # Shared sections (same as triage report)
    _render_demographics(pdf, patient)
    _render_vitals(pdf, patient)
    _render_asr(pdf, patient)
    _render_ehr_risk_flags(pdf, patient)
    _render_triage_result(pdf, patient)
    _render_cross_engine(pdf, patient)
    _render_nurse_override(pdf, patient)

    # Differential Diagnosis
    da = patient.differential_agreement
    if da:
        pdf.section_heading("Differential Diagnosis")

        all_agree = _get_val(da, "all_agree", [])
        if all_agree:
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_x(pdf.l_margin)
            pdf.cell(0, 6, "Primary (Consensus - >=80% agreement):", new_x="LMARGIN", new_y="NEXT")
            for c in all_agree:
                prob_val = _get_val(c, "probability")
                prob = f"{prob_val:.0%}" if prob_val is not None else "N/A"
                dm = " [DON'T MISS]" if _get_val(c, "is_dont_miss", False) else ""
                old_lm = pdf.l_margin
                indent_x = old_lm + 4
                pdf.set_font("Helvetica", "", 9)
                pdf.set_x(indent_x)
                pdf.set_left_margin(indent_x)
                pdf.multi_cell(0, 5, f"{_get_val(c, 'diagnosis')} ({prob}){dm}")
                
                evidence = _get_val(c, "supporting_evidence", [])
                if evidence:
                    ev_indent = old_lm + 8
                    pdf.set_font("Helvetica", "I", 8)
                    pdf.set_text_color(*_MUTED_RGB)
                    evidence_text = "; ".join(evidence[:3])
                    pdf.set_x(ev_indent)
                    pdf.set_left_margin(ev_indent)
                    pdf.multi_cell(0, 4, f"Evidence: {evidence_text}")
                    pdf.set_text_color(*_BLACK)
                pdf.set_left_margin(old_lm)

        some_agree = _get_val(da, "some_agree", [])
        if some_agree:
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_x(pdf.l_margin)
            pdf.cell(0, 6, "Alternative (Partial - 40-79% agreement):", new_x="LMARGIN", new_y="NEXT")
            for c in some_agree:
                prob_val = _get_val(c, "probability")
                prob = f"{prob_val:.0%}" if prob_val is not None else "N/A"
                dm = " [DON'T MISS]" if _get_val(c, "is_dont_miss", False) else ""
                old_lm = pdf.l_margin
                indent_x = old_lm + 4
                pdf.set_font("Helvetica", "", 9)
                pdf.set_x(indent_x)
                pdf.set_left_margin(indent_x)
                pdf.multi_cell(0, 5, f"{_get_val(c, 'diagnosis')} ({prob}){dm}")
                pdf.set_left_margin(old_lm)

        devil = _get_val(da, "devil_advocate_only", [])
        if devil:
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_x(pdf.l_margin)
            pdf.cell(0, 6, "Minority (Devil's Advocate - <40%):", new_x="LMARGIN", new_y="NEXT")
            for c in devil:
                prob_val = _get_val(c, "probability")
                prob = f"{prob_val:.0%}" if prob_val is not None else "N/A"
                dm = " [DON'T MISS]" if _get_val(c, "is_dont_miss", False) else ""
                old_lm = pdf.l_margin
                indent_x = old_lm + 4
                pdf.set_font("Helvetica", "", 9)
                pdf.set_x(indent_x)
                pdf.set_left_margin(indent_x)
                pdf.multi_cell(0, 5, f"{_get_val(c, 'diagnosis')} ({prob}){dm}")
                pdf.set_left_margin(old_lm)

        dont_miss_all = _get_val(da, "dont_miss_all", [])
        if dont_miss_all:
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*_ERROR_RGB)
            pdf.cell(0, 5, "Don't-Miss Diagnoses (any model):", new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(*_BLACK)
            for dx in dont_miss_all:
                pdf.bullet(dx)
        pdf.ln(3)

    # Ensemble Management Recommendations
    ma = patient.management_agreement
    if ma:
        common_inv = _get_val(ma, "common_investigations", [])
        common_img = _get_val(ma, "common_imaging", [])
        common_med = _get_val(ma, "common_medications", [])
        has_consensus = common_inv or common_img or common_med

        if has_consensus:
            pdf.section_heading("Ensemble Management Recommendations")
            _render_management_category(pdf, "Investigations (Consensus)", common_inv)
            _render_management_category(pdf, "Imaging (Consensus)", common_img)
            _render_management_category(pdf, "Medications (Consensus)", common_med)
        else:
            pdf.section_heading("Management Recommendations")
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(*_MUTED_RGB)
            pdf.multi_cell(0, 5, "No consensus across models. Individual model recommendations shown below.")
            pdf.set_text_color(*_BLACK)
            pdf.ln(2)

        # Disposition votes
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(0, 6, "Disposition:", new_x="LMARGIN", new_y="NEXT")
        cons_disp = _get_val(ma, "consensus_disposition")
        if cons_disp:
            pdf.set_font("Helvetica", "", 9)
            pdf.cell(0, 5, f"  Consensus: {str(cons_disp).title()}", new_x="LMARGIN", new_y="NEXT")
        
        disp_votes = _get_val(ma, "disposition_votes", {})
        if disp_votes:
            pdf.set_font("Helvetica", "I", 8)
            pdf.set_text_color(*_MUTED_RGB)
            votes_str = ", ".join(f"{str(d).title()}: {c}" for d, c in disp_votes.items())
            pdf.cell(0, 5, f"  Votes: {votes_str}", new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(*_BLACK)

        # Individual model items
        _render_individual_model_items(pdf, patient, promoted=not has_consensus)

        # Contraindications
        contra = _get_val(ma, "contraindications", [])
        if contra:
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*_ERROR_RGB)
            pdf.cell(0, 5, "Contraindications Flagged:", new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(*_BLACK)
            for ci in contra:
                pdf.bullet(ci)
        pdf.ln(3)

    # Approved Management Plan (physician selections)
    if patient.is_signed_off or patient.physician_approved_investigations or patient.physician_approved_imaging or patient.physician_approved_medications:
        pdf.section_heading("Physician-Approved Plan")
        _render_approved_list(pdf, "Investigations", patient.physician_approved_investigations)
        _render_approved_list(pdf, "Imaging", patient.physician_approved_imaging)
        _render_approved_list(pdf, "Medications", patient.physician_approved_medications)
        pdf.kv("Disposition", (patient.physician_disposition or "Not specified").title())
        pdf.ln(3)

    # Physician Notes
    if patient.physician_notes:
        pdf.section_heading("Physician Notes")
        pdf.set_font("Helvetica", "", 9)
        pdf.multi_cell(0, 5, patient.physician_notes)
        pdf.ln(3)

    # Sign-off
    pdf.section_heading("Physician Sign-Off")
    if patient.is_signed_off:
        pdf.kv("Status", "SIGNED OFF", bold_value=True)
        pdf.kv("Physician", patient.physician_name or "Unknown")
        pdf.kv(
            "Signed at",
            patient.physician_sign_off.strftime("%Y-%m-%d %H:%M:%S"),
        )
    else:
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*_ERROR_RGB)
        pdf.cell(0, 7, "DRAFT - PENDING SIGN-OFF", new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(*_BLACK)

    # Timestamp
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(
        0, 5,
        f"Report generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        new_x="LMARGIN", new_y="NEXT",
    )

    return bytes(pdf.output())
